'use strict';
/* =====================================================================
   ECHO — PR15.5-C · HURT/DEATH — REAÇÃO AO DANO, IDENTIDADE MATERIAL
   E MORTE POR FAMÍLIA
   ---------------------------------------------------------------------
   Suíte de segurança do pipeline mais perigoso do jogo: MORTE toca
   reward/XP/drops/splitter/singular/phantom. Por isso cobre:
   · perfis de impacto (inventário, O(1), sem stats mecânicos);
   · hurt lazy, coalescente, com direção da ORIGEM REAL do dano;
   · reação por família (leve/pesado/energia/espectral/cristal/
     anômalo/invocador/enxame);
   · corpse visual: cap, lifetime, pool, pureza, zero gameplay;
   · reward/XP/drop/KILL exatamente uma vez (incl. comparação contra
     a base mecânica 5d8e244 em mundo isolado com RNG semeado);
   · splitter/phantom/singular/bulwark/swarm com invariantes próprios;
   · Save/Continue, Sandbox, DEV;
   · pureza de draw, determinismo, RNG mecânico intacto;
   · fast path idle byte-idêntico à base (hash do canvas).
   ===================================================================== */
const assert=require('assert');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const Module=require('module');
const {T,SRC,sandbox}=require('../audit_pr135/harness.js');
const {readSource}=require('../audit_pr155/performance_benchmark.js');
let passed=0,failed=0;
function ok(label,fn){try{fn();passed++;console.log('  ✔ '+label);}catch(e){failed++;console.log('  ✘ '+label+' → '+(e&&e.message||e));}}
const near=(a,b,e=1e-9)=>Math.abs(a-b)<=e;
const DT=1/60;
const ROOT=path.resolve(__dirname,'..');
const BASE_REF='5d8e244c22b1a505c1cd25c4149497f91c83871a';
const IDS=['chaser','shooter','tank','spawner','anomaly','swarm','orbiter','bulwark','splitter','phantom','singular'];
const TYPES=Object.keys(T.EDEFS);
/* ---- mundo isolado da BASE (commit 5d8e244) p/ comparação mecânica ---- */
let _before=null;
function beforeWorld(){
  if(_before)return _before;
  const source=readSource(BASE_REF);
  const filename=path.join(ROOT,'audit_pr135/harness.js');
  let code=fs.readFileSync(filename,'utf8');
  if(!source.includes('ENEMY_IMPACT_PROFILES')){
    code=code.split('\n').filter(l=>!l.includes('ENEMY_IMPACT_PROFILES')&&!/PR15\.5-C: reação/.test(l)).join('\n');
  }
  code=code.replace(/^const html=.*;$/m,()=>'const html='+JSON.stringify(source)+';');
  const m=new Module(filename,module);m.filename=filename;m.paths=module.paths;m._compile(code,filename);
  const h=m.exports;
  h.sandbox.Math=Object.create(Math);
  const {performance}=require('perf_hooks');
  h.sandbox.performance.now=()=>performance.now();
  let seed=1;
  h.sandbox.Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  h.seed=v=>{seed=v>>>0;};
  h.run=code2=>vm.runInContext(code2,h.sandbox);
  h.run('DEV_MODE=true;sandboxRun=true;');
  _before=h;return h;
}
/* seed determinístico L-CG sobre o Math.random de um sandbox (restaura) */
function withSeed(sbx,seed,fn){
  let s=seed>>>0;
  const orig=sbx.Math.random;
  sbx.Math.random=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};
  try{return fn();}finally{sbx.Math.random=orig;}
}
const run=c=>vm.runInContext(c,sandbox);
/* ---- canvas ops (mock) ---- */
function opsOf(fn){sandbox.__ctxLog=[];try{fn();}catch(e){sandbox.__ctxLog=null;throw e;}const l=sandbox.__ctxLog;sandbox.__ctxLog=null;return l;}
const nOp=(l,op)=>l.reduce((n,e)=>n+(e[0]===op?1:0),0);
const blurPos=l=>l.filter(e=>e[0]==='set:shadowBlur'&&e[1][0]>0).length;
const argsFinite=l=>l.every(e=>(e[1]||[]).every(a=>typeof a!=='number'||Number.isFinite(a)));
const hashLog=l=>crypto.createHash('sha256').update(JSON.stringify(l)).digest('hex');
function fresh(){T.startRun();T.setEnemies([]);T.setProjectiles([]);T.setSwings([]);T.deathVisualClear();run('xporbs.length=0');return T.getPlayer();}
function enemy(type,x,y,wave=3){const e=T.spawnEnemy(type,x==null?500:x,y==null?400:y,wave);e.spawnT=0;return e;}
function drawOps(e){return opsOf(()=>T.drawEnemy(e));}
const DBLOCK=()=>SRC.slice(SRC.indexOf('PR15.5-C · HURT / DEATH'),SRC.indexOf('function weaponVisualProfileBuild'));
const RANGED_WI=T.WEAPONS.findIndex(w=>!w.melee);
console.log('\nECHO — PR15.5-C · HURT/DEATH — REAÇÃO, MATERIAL E MORTE');

/* ============ A · INVENTÁRIO E PERFIS DE IMPACTO ============ */
ok('A01 os 11 inimigos comuns do EDEFS têm perfil de impacto',()=>{assert.strictEqual(TYPES.length,11);IDS.forEach(id=>assert.ok(T.ENEMY_IMPACT_PROFILES[id],id));});
ok('A02 tabela de perfis é congelada (pré-computada/fixa)',()=>{assert.ok(Object.isFrozen(T.ENEMY_IMPACT_PROFILES));IDS.forEach(id=>{const p=T.ENEMY_IMPACT_PROFILES[id];assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.hurt));assert.ok(Object.isFrozen(p.death));});});
ok('A03 tabela tem exatamente 11 entradas (não cresce)',()=>assert.strictEqual(Object.keys(T.ENEMY_IMPACT_PROFILES).length,11));
ok('A04 lookup O(1) retorna a MESMA referência congelada',()=>{const a=T.enemyImpactVisualProfile('chaser'),b=T.enemyImpactVisualProfile({type:'chaser'}),c=T.enemyImpactVisualProfile('chaser');assert.strictEqual(a,b);assert.strictEqual(a,c);assert.strictEqual(a,T.ENEMY_IMPACT_PROFILES.chaser);});
ok('A05 perfis NÃO duplicam stats mecânicos',()=>IDS.forEach(id=>{const p=T.ENEMY_IMPACT_PROFILES[id];['hp','spd','dmg','xp','armor','range','cooldown','knockback','hitbox','r','damage'].forEach(k=>{assert.ok(!(k in p),id+'.'+k);assert.ok(!(k in p.hurt),id+'.hurt.'+k);assert.ok(!(k in p.death),id+'.death.'+k);});}));
ok('A06 fallback existe, congelado, SEM corpse (death:null)',()=>{const f=T.ENEMY_IMPACT_PROFILE_FALLBACK;assert.ok(Object.isFrozen(f));assert.strictEqual(f.death,null);['boss','miniboss','shadow','__inexistente__'].forEach(t=>assert.strictEqual(T.enemyImpactVisualProfile(t),f));assert.strictEqual(T.enemyImpactVisualProfile(null),f);assert.strictEqual(T.enemyImpactVisualProfile(undefined),f);});
ok('A07 todos os campos numéricos dos perfis são finitos',()=>IDS.forEach(id=>{const p=T.ENEMY_IMPACT_PROFILES[id];Object.values(p.hurt).concat(Object.values(p.death)).filter(v=>typeof v==='number').forEach(v=>assert.ok(Number.isFinite(v),id));}));
ok('A08 durações de hurt bounded em (0,.2] s',()=>IDS.forEach(id=>{const d=T.ENEMY_IMPACT_PROFILES[id].hurt.duration;assert.ok(d>0&&d<=.2,id+' '+d);}));
ok('A09 durações de death bounded em [.12,.40] s',()=>IDS.forEach(id=>{const d=T.ENEMY_IMPACT_PROFILES[id].death.duration;assert.ok(d>=.12&&d<=.4,id+' '+d);}));
ok('A10 estilos de morte do vocabulário material',()=>{const STYLES=new Set(['snap','flicker','collapse','plate-fall','core-collapse','dissolve','implode','divide','phase-out','implosion']);IDS.forEach(id=>assert.ok(STYLES.has(T.ENEMY_IMPACT_PROFILES[id].death.style),id));});
ok('A11 famílias de massa cobrem o arsenal real',()=>{const fam=id=>T.ENEMY_IMPACT_PROFILES[id].massClass;assert.strictEqual(fam('chaser'),'light');assert.strictEqual(fam('swarm'),'tiny');assert.strictEqual(fam('tank'),'heavy');assert.strictEqual(fam('bulwark'),'heavy');assert.strictEqual(fam('spawner'),'heavy');assert.strictEqual(fam('shooter'),'light');assert.strictEqual(fam('orbiter'),'light');assert.strictEqual(fam('anomaly'),'anomalous');assert.strictEqual(fam('splitter'),'medium');assert.strictEqual(fam('phantom'),'spectral');assert.strictEqual(fam('singular'),'anomalous');});
ok('A12 nenhum array dentro dos perfis (dados escalares)',()=>IDS.forEach(id=>assert.ok(!Object.values(T.ENEMY_IMPACT_PROFILES[id]).some(Array.isArray),id)));
ok('A13 offsets de hurt pequenos (≤ .35·r) — render-only',()=>IDS.forEach(id=>assert.ok(T.ENEMY_IMPACT_PROFILES[id].hurt.offset<=.35,id)));
ok('A14 rotações de hurt discretas (≤ .06 rad)',()=>IDS.forEach(id=>assert.ok(T.ENEMY_IMPACT_PROFILES[id].hurt.rotation<=.06,id)));
ok('A15 squash/stretch ≤ .25 (deformação, não distorção)',()=>IDS.forEach(id=>{const h=T.ENEMY_IMPACT_PROFILES[id].hurt;assert.ok(h.squash<=.25&&h.stretch<=.25,id);}));
ok('A16 catálogos mecânicos intactos (11 tipos, 27 armas, 8 minibosses)',()=>{assert.strictEqual(IDS.length,11);assert.strictEqual(T.WEAPONS.length,27);assert.strictEqual(T.MINIBOSS.length,8);});
ok('A17 assinatura EDEFS idêntica à base',()=>assert.strictEqual(Object.entries(T.EDEFS).map(([k,d])=>[k,d.hp,d.spd,d.r,d.dmg,d.xp].join(':')).join('|'),'chaser:26:238:13:10:5|shooter:36:150:15:8:7|tank:150:66:27:32:15|spawner:125:34:24:12:18|anomaly:44:186:14:18:12|swarm:12:322:9:6:3|orbiter:34:205:12:9:6|bulwark:78:112:18:16:9|splitter:62:168:16:13:11|phantom:30:212:13:15:14|singular:190:96:24:24:30'));
ok('A18 waveCompBase idêntico à base (ondas 1–20)',()=>{const b=beforeWorld();for(let w=1;w<=20;w++)assert.strictEqual(JSON.stringify(T.waveComp(w)),JSON.stringify(b.T.waveComp(w)),'onda '+w);});
ok('A19 MINIBOSS idêntico à base',()=>assert.strictEqual(JSON.stringify(T.MINIBOSS),JSON.stringify(beforeWorld().T.MINIBOSS)));
ok('A20 pose de hurt NÃO lê stats mecânicos no render (texto)',()=>{const f=SRC.slice(SRC.indexOf('function visualHurtPose'),SRC.indexOf('function visualWeaponRecoil'));assert.ok(!/\.hp\b|\.maxHp|\.dmg\b|\.spd\b|armor/.test(f));});
ok('A21 perfil por tipo é estável entre chamadas (precomputado)',()=>{const s=new Set();for(let i=0;i<50;i++)s.add(T.enemyImpactVisualProfile('tank'));assert.strictEqual(s.size,1);});

/* ============ B · ESTADO LAZY / COALESCENTE ============ */
ok('B01 visualPeek não cria estado',()=>{const e={x:0,y:0};assert.strictEqual(T.visualPeek(e),null);assert.ok(!('visual'in e));});
ok('B02 tick sem estado não cria estado',()=>{const e={x:0,y:0};T.visualTimelineTick(e,.016);assert.ok(!('visual'in e));});
ok('B03 drawEnemy idle não cria estado',()=>{const e={x:100,y:100,aim:0,r:13,hp:10,maxHp:10,flashT:0,spawnT:0,type:'chaser',color:'#fff',fireT:9,strafe:1,slowT:0,touchCd:0};T.drawEnemy(e);assert.ok(!('visual'in e));});
ok('B04 46 inimigos que nunca são atingidos NÃO ganham estado',()=>{fresh();const es=[];for(let i=0;i<46;i++)es.push(enemy('chaser',100+(i%10)*60,100+((i/10)|0)*60));es.forEach(e=>T.updateEnemy(e,0));es.forEach(e=>T.drawEnemy(e));assert.strictEqual(es.filter(e=>e.visual).length,0);});
ok('B05 acerto real cria o estado (lazy no evento)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);assert.ok(!e.visual);T.damageEnemy(e,1,p.x,p.y,false,false);assert.ok(e.visual&&e.visual.event==='hurt');});
ok('B06 contrato da fundação preservado (≤20 chaves em visual)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,1,p.x,p.y,false,false);assert.ok(Object.keys(e.visual).length<=20);});
ok('B07 10000 hits coalescentes: O(1), sem arrays, chaves estáveis',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);for(let i=0;i<10000;i++)T.damageEnemy(e,1,p.x-40+i%30,p.y,false,false);assert.ok(Object.keys(e.visual).length<=20);assert.ok(!Object.values(e.visual).some(Array.isArray));assert.strictEqual(e.visual.event,'hurt');});
ok('B08 origem NaN/Infinity/undefined é neutralizada',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,NaN,Infinity);assert.ok(Number.isFinite(e.visual.hitX)&&Number.isFinite(e.visual.hitY));T.visualNotifyHurt(e,undefined,undefined);assert.ok(Number.isFinite(e.visual.hitX)&&Number.isFinite(e.visual.hitY));});
ok('B09 valores finitos após dano com coordenadas inválidas',()=>{const p=fresh();const e=enemy('chaser',NaN,NaN);T.damageEnemy(e,5,0,0,false,false);const v=e.visual;assert.ok(Number.isFinite(v.hitX)&&Number.isFinite(v.hitY));assert.ok(Object.values(v).filter(x=>typeof x==='number').every(Number.isFinite));});
ok('B10 último hit vence (coalescência, sem fila)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,1,p.x,p.y,false,false);T.damageEnemy(e,1,p.x+100,p.y-200,false,false);const v=e.visual;assert.ok(v.eventT>0);assert.ok(Math.abs(v.hitY-1)<1e-9,'2º hit de cima: hitY=+1');assert.ok(Math.abs(v.hitX)<1e-9,'2º hit: hitX≈0');});
ok('B11 direção vem da ORIGEM REAL do dano',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,1,p.x,p.y,false,false);assert.ok(e.visual.hitX>0.99,'origem à esquerda → empurra +X');T.damageEnemy(e,1,p.x+200,p.y,false,false);assert.ok(e.visual.hitX<-0.99,'origem à direita → empurra -X');});
ok('B12 origem colapsada usa fallback determinístico (aim)',()=>{const p=fresh();const a=enemy('chaser',p.x+100,p.y),b=enemy('chaser',p.x+150,p.y);a.aim=0;b.aim=0;T.visualNotifyHurt(a,a.x,a.y);T.visualNotifyHurt(b,b.x,b.y);assert.ok(near(a.visual.hitX,b.visual.hitX,1e-9)&&near(a.visual.hitY,b.visual.hitY,1e-9));assert.ok(a.visual.hitX>0.99,'fallback = direção do aim');});
ok('B13 hitX/hitY são vetor unitário (|v|≈1)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,p.x-200,p.y+100);const L=Math.hypot(e.visual.hitX,e.visual.hitY);assert.ok(Math.abs(L-1)<1e-9);});
ok('B14 phase empacotado em 0..3 (int)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);for(const [sx,sy] of [[p.x,p.y],[p.x+200,p.y],[p.x+100,p.y-200],[p.x+100,p.y+200],[p.x-100,p.y+100]]){T.visualNotifyHurt(e,sx,sy);assert.ok(e.visual.phase>=0&&e.visual.phase<=3&&Number.isInteger(e.visual.phase));}});

/* ============ C · PIPELINE DE HURT ============ */
ok('C01 hurt começa no evento REAL de dano (damageEnemy)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);assert.ok(!e.visual);T.damageEnemy(e,1,p.x,p.y,false,false);assert.strictEqual(e.visual.event,'hurt');assert.ok(e.visual.eventT>0);});
ok('C02 flash legado preservado no acerto',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,1,p.x,p.y,false,false);assert.ok(e.flashT>0);});
ok('C03 duração do hurt por família',()=>{const p=fresh();const c=enemy('chaser',p.x+60,p.y),s=enemy('swarm',p.x+90,p.y),t=enemy('tank',p.x+120,p.y);T.damageEnemy(c,1,p.x,p.y,false,false);T.damageEnemy(s,1,p.x,p.y,false,false);T.damageEnemy(t,1,p.x,p.y,false,false);assert.strictEqual(c.visual.duration,T.ENEMY_IMPACT_PROFILES.chaser.hurt.duration);assert.strictEqual(s.visual.duration,T.ENEMY_IMPACT_PROFILES.swarm.hurt.duration);assert.strictEqual(t.visual.duration,T.ENEMY_IMPACT_PROFILES.tank.hurt.duration);});
ok('C04 DoT também registra hurt (mesmo evento)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,2,p.x,p.y-1,false,true);assert.strictEqual(e.visual.event,'hurt');});
ok('C05 intangível NÃO registra hurt (sem dano, sem evento)',()=>{const p=fresh();const e=enemy('phantom',p.x+100,p.y);e.ghostT=.5;const hp0=e.hp;T.damageEnemy(e,10,p.x,p.y,false,false);assert.strictEqual(e.hp,hp0,'sem dano');assert.ok(!e.visual||e.visual.event!=='hurt','sem evento de hurt');});
ok('C06 anômalo fora de fase não registra hurt',()=>{const p=fresh();const e=enemy('anomaly',p.x+100,p.y);e.phaseT=.3;const hp0=e.hp;T.damageEnemy(e,10,p.x,p.y,false,false);assert.strictEqual(e.hp,hp0);assert.ok(!e.visual||e.visual.event!=='hurt');});
ok('C07 bulwark bloqueado (dano reduzido) ainda registra hurt',()=>{const p=fresh();const e=enemy('bulwark',p.x+100,p.y);e.shieldAng=0;const hp0=e.hp;T.damageEnemy(e,10,p.x,p.y,false,false);assert.ok(e.hp<hp0,'dano reduzido aplica');assert.strictEqual(e.visual.event,'hurt');});
ok('C08 expirado retorna null (fast path)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,0,0);T.visualTimelineTick(e,1);assert.strictEqual(T.visualHurtPose(e),null);});
ok('C09 reutiliza scratch fornecido (zero alocação)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,0,0);const out={};assert.strictEqual(T.visualHurtPose(e,out),out);});
ok('C10 ZERO trig por frame na pose ativa (antes: atan2/frame)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,p.x-100,p.y);const trig=wrapTrig(()=>{for(let i=0;i<100;i++)T.visualHurtPose(e);});assert.strictEqual(trig.atan2,0,'sem atan2');assert.strictEqual(trig.cos,0);assert.strictEqual(trig.sin,0);});
ok('C11 11 tipos: pose ativa finita',()=>{fresh();IDS.forEach(id=>{const e=enemy(id,500,400);T.visualNotifyHurt(e,300,200);const p=T.visualHurtPose(e);assert.ok(p,id);['offsetX','offsetY','rotation','scaleX','scaleY','lean','alpha'].forEach(k=>assert.ok(Number.isFinite(p[k]),id+'.'+k));});});
ok('C12 hurt NÃO cancela ataque em curso',()=>{const p=fresh();const e=enemy('shooter',p.x+100,p.y);T.visualAttackTrigger(e,0,10,'shot',1);T.visualNotifyHurt(e,p.x-1,p.y);assert.strictEqual(e.visual.attackState,'active');assert.strictEqual(e.visual.event,'hurt');});
ok('C13 visualNotifyHurt retorna o estado',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);assert.strictEqual(T.visualNotifyHurt(e,1,2),e.visual);});
ok('C14 drawEnemy com hurt: entidade não é mutada (draw puro)',()=>{fresh();IDS.forEach(id=>{const e=enemy(id,500,400);T.damageEnemy(e,1,300,300,false,false);const b=JSON.stringify(e);T.drawEnemy(e);assert.strictEqual(JSON.stringify(e),b,id);});});
ok('C15 hurt ativo: exatamente 1 translate/rotate/scale extra',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);const a=drawOps(e);T.visualNotifyHurt(e,p.x-100,p.y);const b=drawOps(e);assert.strictEqual(nOp(b,'translate')-nOp(a,'translate'),1);assert.strictEqual(nOp(b,'rotate')-nOp(a,'rotate'),1);assert.strictEqual(nOp(b,'scale')-nOp(a,'scale'),1);});
ok('C16 hurt expirado volta ao nº original de transforms',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);const a=drawOps(e);T.visualNotifyHurt(e,p.x-100,p.y);T.visualTimelineTick(e,1);const b=drawOps(e);assert.deepStrictEqual([nOp(b,'translate'),nOp(b,'rotate'),nOp(b,'scale')],[nOp(a,'translate'),nOp(a,'rotate'),nOp(a,'scale')]);});
function wrapTrig(fn){const M=sandbox.Math;const c={atan2:0,cos:0,sin:0,hypot:0};const o={};for(const k of Object.keys(c)){o[k]=M[k];M[k]=function(){c[k]++;return o[k].apply(this,arguments);};}try{fn();}finally{for(const k of Object.keys(c))M[k]=o[k];}return c;}

/* ============ D · REAÇÃO POR MASSA/MATERIAL ============ */
ok('D01 leve recua mais que pesado (offset)',()=>{const L=T.ENEMY_IMPACT_PROFILES.chaser.hurt.offset,P=T.ENEMY_IMPACT_PROFILES.tank.hurt.offset;assert.ok(L>2*P,'chaser .30 vs tank .06');});
ok('D02 leve gira mais que pesado (rotação)',()=>{const L=T.ENEMY_IMPACT_PROFILES.chaser.hurt.rotation,P=T.ENEMY_IMPACT_PROFILES.tank.hurt.rotation;assert.ok(L>2*P);});
ok('D03 pesado: deslocamento ≤ .07·r e rotação ≤ .02 rad',()=>{['tank','bulwark','spawner','singular'].forEach(id=>{const h=T.ENEMY_IMPACT_PROFILES[id].hurt;assert.ok(h.offset<=.07&&h.rotation<=.02,id);});});
ok('D04 energético: sem deslocamento/rotação (distorção interna)',()=>{['shooter','orbiter'].forEach(id=>{const h=T.ENEMY_IMPACT_PROFILES[id].hurt;assert.strictEqual(h.offset,0);assert.strictEqual(h.rotation,0);assert.ok(h.intensity>0,'lean ativo p/ distorção');});});
ok('D05 shooter: hurt muda o orbe (raio) sem adicionar ops',()=>{fresh();const e=enemy('shooter',500,400);const a=drawOps(e);T.visualNotifyHurt(e,400,300);const b=drawOps(e);assert.strictEqual(nOp(b,'arc'),nOp(a,'arc'),'mesmo nº de arcos');assert.strictEqual(nOp(b,'beginPath'),nOp(a,'beginPath'),'mesmo nº de paths');assert.notDeepStrictEqual(b,a,'argumentos mudam (flicker)');});
ok('D06 orbiter: dessincronização sem ops novos',()=>{fresh();const e=enemy('orbiter',500,400);const a=drawOps(e);T.visualNotifyHurt(e,400,300);const b=drawOps(e);assert.strictEqual(nOp(b,'arc'),nOp(a,'arc'));assert.strictEqual(nOp(b,'beginPath'),nOp(a,'beginPath'));assert.notDeepStrictEqual(b,a,'dashOffset/raio mudam');});
ok('D07 espectral: dip de alpha no pose',()=>{fresh();const e=enemy('phantom',500,400);T.visualNotifyHurt(e,300,400);const p=T.visualHurtPose(e);assert.ok(p.alpha<1&&p.alpha>0,'alpha reduzido');});
ok('D08 phantom: eco de fase = exatamente 1 path+stroke extra',()=>{fresh();const e=enemy('phantom',500,400);const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'beginPath')-nOp(a,'beginPath'),1,'1 path extra (eco)');assert.strictEqual(nOp(b,'stroke')-nOp(a,'stroke'),1);assert.strictEqual(nOp(b,'translate')-nOp(a,'translate'),1,'só o translate do pose');});
ok('D09 cristalino: microfissura sem path novo (geometria abre)',()=>{fresh();const e=enemy('splitter',500,400);const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'beginPath'),nOp(a,'beginPath'));assert.notDeepStrictEqual(b,a,'splitGap cresce');});
ok('D10 anômalo: jitter ampliado com MESMA contagem de aleatoriedade',()=>{fresh();const e=enemy('anomaly',500,400);const M=sandbox.Math,orig=M.random;let rnd=0;M.random=function(){rnd++;return orig();};sandbox.__ctxLog=[];T.drawEnemy(e);const idleRnd=rnd;const idleLog=sandbox.__ctxLog;sandbox.__ctxLog=null;T.visualNotifyHurt(e,300,400);sandbox.__ctxLog=[];rnd=0;T.drawEnemy(e);M.random=orig;const hurtLog=sandbox.__ctxLog;sandbox.__ctxLog=null;assert.strictEqual(rnd,idleRnd,'mesmo nº de rand()');assert.strictEqual(nOp(hurtLog,'fill'),nOp(idleLog,'fill'));assert.notDeepStrictEqual(hurtLog,idleLog,'amplitude muda');});
ok('D11 singular: compressão radial sem ops novos',()=>{fresh();const e=enemy('singular',500,400);e.pulseA=1;const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'arc'),nOp(a,'arc'),'mesmo nº de anéis');assert.notDeepStrictEqual(b,a,'raios comprimem');});
ok('D12 spawner: fenda reage sem ops novos',()=>{fresh();const e=enemy('spawner',500,400);const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'arc'),nOp(a,'arc'));assert.strictEqual(nOp(b,'beginPath'),nOp(a,'beginPath'));assert.notDeepStrictEqual(b,a);});
ok('D13 swarm: barato — só o pose (1 transform extra), zero path novo',()=>{fresh();const e=enemy('swarm',500,400);const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'translate')-nOp(a,'translate'),1);assert.strictEqual(nOp(b,'beginPath')-nOp(a,'beginPath'),0);assert.strictEqual(nOp(b,'ellipse')-nOp(a,'ellipse'),0);assert.strictEqual(nOp(b,'fill')-nOp(a,'fill'),0);const p=T.visualHurtPose(e);assert.ok(Math.hypot(p.offsetX,p.offsetY)<=.21*e.r+1e-9);});
ok('D14 tank: peça pesada atrasa sem ops novos',()=>{fresh();const e=enemy('tank',500,400);const a=drawOps(e);T.visualNotifyHurt(e,300,400);const b=drawOps(e);assert.strictEqual(nOp(b,'fillRect'),nOp(a,'fillRect'));assert.notDeepStrictEqual(b,a,'canhão desloca');});
ok('D15 bulwark: placa cede sem ops novos (centro desloca)',()=>{fresh();const e=enemy('bulwark',500,400);e.shieldAng=0;const a=drawOps(e);T.visualNotifyHurt(e,400,400);const b=drawOps(e);assert.strictEqual(nOp(b,'arc'),nOp(a,'arc'));assert.notDeepStrictEqual(b,a,'placa comprime');});
ok('D16 pesado: sensação de massa (squash ≥ stretch, offset mínimo)',()=>{['tank','bulwark','spawner'].forEach(id=>{const h=T.ENEMY_IMPACT_PROFILES[id].hurt;assert.ok(h.squash>=h.stretch,id);assert.ok(h.offset<.1,id);});});
ok('D17 energético: dip de alpha no pose',()=>{fresh();['shooter','orbiter'].forEach(id=>{const e=enemy(id,500,400);T.visualNotifyHurt(e,300,400);assert.ok(T.visualHurtPose(e).alpha<1,id);});});

/* ============ E · CORPSE / DEATH VISUAL — SEGURANÇA ============ */
ok('E01 kill de comum cria exatamente 1 corpse',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);assert.strictEqual(e.dead,true);assert.strictEqual(T.getDeathVisuals().length,1);});
ok('E02 boss/miniboss NÃO geram corpse (fora do escopo, fallback)',()=>{const p=fresh();const b=Object.assign(enemy('chaser',p.x+100,p.y),{type:'boss'});T.damageEnemy(b,99999,p.x,p.y,false,false);assert.strictEqual(T.getDeathVisuals().length,0,'boss sem corpse');const m=Object.assign(enemy('chaser',p.x+120,p.y),{type:'miniboss',hazards:[],plates:0,plateMax:0});T.damageEnemy(m,99999,p.x,p.y,false,false);assert.strictEqual(T.getDeathVisuals().length,0,'miniboss sem corpse');});
ok('E03 corpse copia SÓ o mínimo visual (10 campos, zero gameplay)',()=>{const p=fresh();const e=enemy('tank',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const d=T.getDeathVisuals()[0];assert.deepStrictEqual(Object.keys(d).sort(),['aim','color','dir','dur','r','seed','t','type','x','y'].sort());['hp','maxHp','vx','vy','dmg','xp','spd','shield','st','dead','r_col'].forEach(k=>assert.ok(!(k in d),'campo indevido: '+k));});
ok('E04 corpse herda a direção REAL do último impacto',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,5,p.x+20,p.y,false,false);T.damageEnemy(e,99999,p.x+20,p.y,false,false);const d=T.getDeathVisuals()[0];assert.ok(Math.abs(d.dir-0)<1e-6,'origem (esq)→inimigo: dir≈0 (+X)');});
ok('E05 bulwark corpse preserva a frente (shieldAng → aim)',()=>{const p=fresh();const e=enemy('bulwark',p.x+100,p.y);e.shieldAng=1.23;T.damageEnemy(e,99999,p.x,p.y,false,false);assert.strictEqual(T.getDeathVisuals()[0].aim,1.23);});
ok('E06 cap: 46 mortes → 24 corpses (descarte O(1) do mais novo)',()=>{const p=fresh();for(let i=0;i<46;i++){const e=enemy('swarm',p.x+10+i*8,p.y,3);T.damageEnemy(e,99999,p.x,p.y,false,false);}assert.strictEqual(T.getDeathVisuals().length,T.DEATH_VISUAL_CAP);assert.strictEqual(T.DEATH_VISUAL_CAP,24);});
ok('E07 descarte determinístico: os 24 primeiros permanecem',()=>{const p=fresh();for(let i=0;i<46;i++){const e=enemy('chaser',p.x+10+i*8,p.y,3);T.damageEnemy(e,99999,p.x,p.y,false,false);}const xs=T.getDeathVisuals().map(d=>Math.round(d.x));assert.strictEqual(xs.length,24);assert.strictEqual(xs[0],Math.round(p.x+10));assert.strictEqual(xs[23],Math.round(p.x+10+23*8));});
ok('E08 lifetime drena todos os corpses',()=>{const p=fresh();const e=enemy('tank',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);for(let i=0;i<40;i++)T.deathVisualTick(DT);assert.strictEqual(T.getDeathVisuals().length,0);});
ok('E09 pool bounded (guarda no código) e 1000 mortes sem growth',()=>{const b=DBLOCK();assert.ok(/deathVisualPool\.length<DEATH_VISUAL_CAP\*2/.test(b),'guarda do pool existe');const p=fresh();for(let i=0;i<1000;i++){const e=enemy('swarm',500,400,3);T.damageEnemy(e,99999,p.x,p.y,false,false);if(i%5===0)T.deathVisualTick(DT);}assert.ok(T.getDeathVisuals().length<=T.DEATH_VISUAL_CAP);T.deathVisualClear();});
ok('E10 tick com dt inválido é seguro',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);T.deathVisualTick(NaN);T.deathVisualTick(-1);assert.ok(T.getDeathVisuals().length>=1);assert.ok(T.getDeathVisuals().every(d=>Number.isFinite(d.t)&&d.t>=0));T.deathVisualTick(99);assert.strictEqual(T.getDeathVisuals().length,0);});
ok('E11 deathVisualPush sem estado visual usa o aim (fallback)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);delete e.visual;e.aim=2.2;T.deathVisualClear();const d=T.deathVisualPush(e);assert.ok(d);assert.ok(Math.abs(d.dir-2.2)<1e-9);});
ok('E12 kills incrementa exatamente 1 por morte',()=>{const p=fresh();const k0=T.getKills();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);assert.strictEqual(T.getKills()-k0,1);});
ok('E13 XP exatamente uma vez (orbs somam o xp exato do inimigo)',()=>{const p=fresh();const e=enemy('shooter',p.x+100,p.y);const xp0=e.xp;T.damageEnemy(e,99999,p.x,p.y,false,false);assert.strictEqual(run('xporbs.reduce((a,o)=>a+o.v,0)'),xp0);assert.ok(run('xporbs.length')>=1);});
ok('E14 créditos do kill idênticos à base (mesma semente)',()=>{const b=beforeWorld();const credit=h=>withSeed(h.sandbox,1234,()=>{h.run('startRun()');return h.run('enemies.length=0;player.x=600;player.y=400;var e=spawnEnemy("chaser",500,400,3);e.spawnT=0;e.aim=0;var c0=player.coins;damageEnemy(e,99999,580,400,false,false);player.coins-c0');});assert.strictEqual(credit({sandbox,run:c=>vm.runInContext(c,sandbox)}),credit(b));});
ok('E15 FX do kill: contagem de particles idêntica à base (mesma semente)',()=>{const b=beforeWorld();const parts=h=>withSeed(h.sandbox,4321,()=>{h.run('startRun()');return h.run('enemies.length=0;parts.length=0;player.x=600;player.y=400;var e=spawnEnemy("chaser",500,400,3);e.spawnT=0;e.aim=0;damageEnemy(e,99999,580,400,false,false);parts.length');});assert.strictEqual(parts({sandbox,run:c=>vm.runInContext(c,sandbox)}),parts(b));});
ok('E16 splitter: exatamente 2 filhos, uma vez (sem duplicar)',()=>{const p=fresh();const e=enemy('splitter',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);let shards=T.getEnemies().filter(x=>x.isShard&&x.type==='splitter');assert.strictEqual(shards.length,2,'2 filhos');for(let i=0;i<30;i++)shards.forEach(s=>T.updateEnemy(s,DT));shards=T.getEnemies().filter(x=>x.isShard&&x.type==='splitter');assert.strictEqual(shards.length,2,'filhos não se multiplicam');});
ok('E17 corpse sob o jogador NÃO causa dano (posição de contato)',()=>{const p=fresh();p.invT=0;p.hp=p.maxHp;const e=enemy('chaser',p.x,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);assert.ok(T.getDeathVisuals().length===1);const hp0=p.hp;for(let i=0;i<12;i++){T.deathVisualTick(DT);T.updatePlayer(DT);}assert.strictEqual(p.hp,hp0,'cadáver sobreposto não toca o jogador');});
ok('E18 corpse fora de targeting/dano: uso estático restrito',()=>{const uses=SRC.match(/deathVisuals/g)||[];assert.ok(uses.length>=8,'sistema presente');const src=SRC.slice(SRC.indexOf('function pickTarget'),SRC.indexOf('function updateEnemy'));assert.ok(!/deathVisual/.test(src),'pickTarget não consulta corpses');const dmg=SRC.slice(SRC.indexOf('function damageEnemy'),SRC.indexOf('function triggerResonance'));assert.ok(!/deathVisual/.test(dmg),'damageEnemy não consulta corpses');});
ok('E19 corpse não chama damageEnemy/killEnemy/callbacks/FX',()=>{const b=DBLOCK();const c=b.slice(b.indexOf('function deathVisualPush'));assert.ok(!/damageEnemy|killEnemy|itemEmit|bumpProg|xporbs|pickups\.push|spawnShards|spawnParticles|spawnRing|Math\.random|setTimeout|setInterval/.test(c),'bloco corpse sem hooks de gameplay');});
ok('E20 Save/Continue: corpse NÃO persiste no checkpoint',()=>{T.activateSlot(1);fresh();const p=T.getPlayer();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);assert.strictEqual(T.getDeathVisuals().length,1);assert.ok(T.captureCheckpoint('teste'),'checkpoint criado');T.resumeRun();assert.strictEqual(T.getDeathVisuals().length,0,'corpse limpo no resume');T.clearActiveRun();});
ok('E21 Sandbox: corpse não atravessa restart do laboratório',()=>{T.sandboxStart();const p=T.getPlayer();const e=enemy('swarm',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);assert.ok(T.getDeathVisuals().length>=1,'corpse existe no sandbox');T.sandboxRestart();assert.strictEqual(T.getDeathVisuals().length,0,'limpo no restart');});
ok('E22 remoção mecânica direta (sem killEnemy) NÃO gera corpse',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);e.dead=true;const i=T.getEnemies().indexOf(e);if(i>=0)T.getEnemies().splice(i,1);assert.strictEqual(T.getDeathVisuals().length,0,'dead direto ≠ abate');});
ok('E23 DEV: remoção do miniboss sem corpse',()=>{const p=fresh();const mb=T.spawnMiniBoss(5,T.MINIBOSS[0]);assert.ok(mb);const i=T.getEnemies().indexOf(mb);if(i>=0)T.getEnemies().splice(i,1);assert.strictEqual(T.getDeathVisuals().length,0);});

/* ============ F · MORTE POR FAMÍLIA — IDENTIDADE ============ */
ok('F01 11 tipos: corpse desenha com args finitos e algo visível',()=>{fresh();IDS.forEach(id=>{const p=T.getPlayer();const e=enemy(id,p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.ok(argsFinite(l),id);assert.ok(l.length>0,id+' desenhou algo');T.deathVisualClear();});});
ok('F02 swarm: morte minimalista (1 fill, 0 stroke)',()=>{const p=fresh();const e=enemy('swarm',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(nOp(l,'fill'),1,'só o corpo');assert.strictEqual(nOp(l,'stroke'),0);T.deathVisualClear();});
ok('F03 leve (chaser): snap + 3 fragmentos no máximo',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.ok(nOp(l,'stroke')<=3,'3 fagulhas');assert.ok(nOp(l,'fill')<=2);T.deathVisualClear();});
ok('F04 pesado (tank): ≤ 5 paths (peças, não explosão)',()=>{const p=fresh();const e=enemy('tank',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.ok(nOp(l,'beginPath')<=5);T.deathVisualClear();});
ok('F05 energético: dissolve de dentro p/ fora, duração curta',()=>{const p=fresh();const e=enemy('shooter',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const d=T.getDeathVisuals()[0];assert.ok(d.dur<=.25);const l1=opsOf(()=>T.drawDeathVisuals());T.deathVisualTick(DT);const l2=opsOf(()=>T.drawDeathVisuals());assert.ok(l1.length>0&&l2.length>0,'desenha ao longo da vida');T.deathVisualClear();});
ok('F06 espectral: dashing + eco, SEM fill de corpo físico',()=>{const p=fresh();const e=enemy('phantom',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(nOp(l,'fill'),0,'sem corpo físico');assert.ok(nOp(l,'stroke')>=2,'contorno + eco');assert.ok(nOp(l,'setLineDash')>=1,'dashing de dissolução');T.deathVisualClear();});
ok('F07 anômalo: implosão (raio do anel CONTRAI com t)',()=>{const p=fresh();const e=enemy('anomaly',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const arcs0=opsOf(()=>T.drawDeathVisuals()).filter(x=>x[0]==='arc').map(x=>x[1]).filter(a=>a.length>=5&&a[3]===0&&a[4]===Math.PI*2).map(a=>a[2]);T.deathVisualTick(DT*10);const arcs1=opsOf(()=>T.drawDeathVisuals()).filter(x=>x[0]==='arc').map(x=>x[1]).filter(a=>a.length>=5&&a[3]===0&&a[4]===Math.PI*2).map(a=>a[2]);assert.ok(arcs0.length&&arcs1.length);assert.ok(Math.max(...arcs1)<Math.max(...arcs0),'anel contrai (implosão, não explosão)');T.deathVisualClear();});
ok('F08 singular: pull mecânico termina no momento da morte (zero residual)',()=>{const p=fresh();p.vx=0;p.vy=0;p.invT=0;const s=enemy('singular',p.x-200,p.y);T.updateEnemy(s,DT);p.vx=0;p.vy=0;T.damageEnemy(s,99999,p.x-100,p.y,false,false);assert.strictEqual(T.getDeathVisuals().length,1);const vx0=p.vx,vy0=p.vy;for(let i=0;i<10;i++){T.deathVisualTick(DT);T.updatePlayer(DT);}assert.ok(Math.abs(p.vx-vx0)<1e-9&&Math.abs(p.vy-vy0)<1e-9,'sem pull residual após a morte');});
ok('F09 splitter: 3 fragmentos angulares GRANDES + filhos íntegros',()=>{const p=fresh();const e=enemy('splitter',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(nOp(l,'fill'),3,'3 shards');const kids=T.getEnemies().filter(x=>x.isShard);assert.strictEqual(kids.length,2);assert.ok(kids.every(k=>k.hp===k.maxHp&&k.maxHp>0&&k.isShard),'filhos nascem íntegros (hp=maxHp)');T.deathVisualClear();});
ok('F10 espectral: fade não-linear (acelera no fim)',()=>{const p=fresh();const e=enemy('phantom',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const d=Object.assign({},T.getDeathVisuals()[0]);T.deathVisualClear();const alphaAt=t=>{T.setDeathVisuals([Object.assign({},d,{t})]);const l=opsOf(()=>T.drawDeathVisuals());T.deathVisualClear();return Math.max(0,...l.filter(x=>x[0]==='set:globalAlpha').map(x=>x[1][0]));};const a1=alphaAt(d.dur*.25),a2=alphaAt(d.dur*.5),a3=alphaAt(d.dur*.75);assert.ok(a1>a2&&a2>a3,'monotônico decrescente');assert.ok(a3<(1-.75),'não-linear: decai mais que o linear no fim');});
ok('F11 corpse determinístico: mesmos campos → mesmo canvas (hash)',()=>{const mk=()=>({x:500,y:400,r:13,type:'chaser',color:'#ff4d6d',aim:0,dir:1,t:.05,dur:.16,seed:.5});T.deathVisualClear();const a=opsOf(()=>{T.setDeathVisuals([mk()]);T.drawDeathVisuals();});const b=opsOf(()=>{T.setDeathVisuals([mk()]);T.drawDeathVisuals();});T.deathVisualClear();assert.strictEqual(hashLog(a),hashLog(b));});
ok('F12 durações por família dentro de [.12,.40]',()=>IDS.forEach(id=>{const d=T.ENEMY_IMPACT_PROFILES[id].death.duration;assert.ok(d>=.12&&d<=.4,id);}));
ok('F13 corpse: ZERO shadowBlur em todas as famílias',()=>{fresh();IDS.forEach(id=>{const p=T.getPlayer();const e=enemy(id,p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(blurPos(l),0,id+' sem blur');T.deathVisualClear();});});
ok('F14 corpse: zero gradientes no draw',()=>{fresh();IDS.forEach(id=>{const p=T.getPlayer();const e=enemy(id,p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.ok(!l.some(x=>x[0]==='createRadialGradient'||x[0]==='createLinearGradient'),id);T.deathVisualClear();});});
ok('F15 drawDeathVisuals vazio = zero ops (fast path)',()=>{T.deathVisualClear();const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(l.length,0);});
ok('F16 corpse offscreen é cullado',()=>{T.deathVisualClear();T.setDeathVisuals([{x:5000,y:5000,r:13,type:'chaser',color:'#fff',aim:0,dir:0,t:0,dur:.16,seed:.5}]);const l=opsOf(()=>T.drawDeathVisuals());T.deathVisualClear();assert.strictEqual(l.length,0,'fora da view → não desenha');});
ok('F17 corpse: save/restore balanceado e bounded',()=>{fresh();IDS.forEach(id=>{const p=T.getPlayer();const e=enemy(id,p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const l=opsOf(()=>T.drawDeathVisuals());assert.strictEqual(nOp(l,'save'),nOp(l,'restore'),id);assert.ok(nOp(l,'save')<=4,id);T.deathVisualClear();});});

/* ============ G · RECOMPENSA EXATAMENTE UMA VEZ ============ */
ok('G01 kill exatamente 1 vez com overkill',()=>{const p=fresh();const k0=T.getKills();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,e.hp+50000,p.x,p.y,false,false);assert.strictEqual(T.getKills()-k0,1);});
ok('G02 onKill emitido exatamente 1 vez',()=>{const p=fresh();run('var __kc=0;var __oe=itemEmit;itemEmit=function(ev,d){if(ev==="onKill")__kc++;return __oe(ev,d);};');run('curAttacker=player');const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const n=run('__kc');run('itemEmit=__oe;curAttacker=null');assert.strictEqual(n,1);});
ok('G03 XP orbs exatamente 1 vez (contagem e soma)',()=>{const p=fresh();const e=enemy('orbiter',p.x+100,p.y);const xp0=e.xp;run('curAttacker=player');T.damageEnemy(e,99999,p.x,p.y,false,false);const n=run('xporbs.length');const sum=run('xporbs.reduce((a,o)=>a+o.v,0)');run('curAttacker=null');assert.strictEqual(sum,xp0);assert.ok(n>=1&&n<=xp0);});
ok('G04 créditos exatamente 1 vez (tick do corpse não re-recompensa)',()=>{const p=fresh();const e=enemy('shooter',p.x+100,p.y);run('curAttacker=player;pickups.length=0');const total=()=>p.coins+run('pickups.filter(k=>k.type==="coin").reduce((a,k)=>a+k.v,0)');const t0=total();T.damageEnemy(e,99999,p.x,p.y,false,false);const d1=total()-t0;run('curAttacker=null');assert.ok(d1>0,'créditos do drop aplicados');for(let i=0;i<10;i++)T.deathVisualTick(DT);assert.strictEqual(total()-t0,d1,'tick do corpse não re-recompensa');});
ok('G05 splitter: filhos spawnam exatamente 1 vez (60 frames depois)',()=>{const p=fresh();const e=enemy('splitter',p.x+100,p.y);run('curAttacker=player');T.damageEnemy(e,99999,p.x,p.y,false,false);run('curAttacker=null');const n1=T.getEnemies().filter(x=>x.isShard).length;for(let i=0;i<60;i++){T.deathVisualTick(DT);T.getEnemies().slice().forEach(x=>{if(!x.dead)T.updateEnemy(x,DT);});}const n2=T.getEnemies().filter(x=>x.isShard).length;assert.strictEqual(n1,2);assert.strictEqual(n2,2,'sem re-spawn por tick');});
ok('G06 tick do corpse nunca re-dispara lógica de morte',()=>{const p=fresh();const k0=T.getKills();const e=enemy('tank',p.x+100,p.y);run('curAttacker=player');T.damageEnemy(e,99999,p.x,p.y,false,false);run('curAttacker=null');for(let i=0;i<200;i++)T.deathVisualTick(DT);assert.strictEqual(T.getKills(),k0+1);});
ok('G07 morte por DoT: reward 1x + corpse',()=>{const p=fresh();const e=enemy('swarm',p.x+100,p.y);const xp0=e.xp;T.damageEnemy(e,9999,p.x,p.y-1,false,true);assert.strictEqual(e.dead,true);assert.strictEqual(run('xporbs.reduce((a,o)=>a+o.v,0)'),xp0);assert.strictEqual(T.getDeathVisuals().length,1);});
ok('G08 morte por status (burn DoT) mantém pipeline',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);e.st={burnT:4,burnP:12,burnSrc:null,bleedT:0,corrT:0,chillP:0,shockT:0,stunT:0,frozen:false};T.damageEnemy(e,e.hp,p.x,p.y-1,false,true);assert.strictEqual(e.dead,true);assert.strictEqual(T.getDeathVisuals().length,1);});

/* ============ H · STRESS ============ */
/* fundo decorativo (dust) é semeado no LOAD do módulo — para isolar a
   comparação ao estado do jogo, normalizamos dust + floor nos dois mundos */
const H01_PRE='startRun();enemies.length=0;projectiles.length=0;parts.length=0;swings.length=0;xporbs.length=0;ftexts.length=0;try{deathVisuals.length=0}catch(e){}dust.length=0;for(let i=0;i<90;i++)dust.push({x:(i*137)%ARENA.w,y:(i*251)%ARENA.h,r:1,a:.1});floorCv=null;';
const H01_SP='var __tt=["chaser","shooter","tank","spawner","anomaly","swarm","orbiter","bulwark","splitter","phantom","singular"];for(let i=0;i<46;i++){var e=spawnEnemy(__tt[i%11],80+(i%10)*58,80+((i/10)|0)*58,3);e.spawnT=0;e.fireT=99;e.aim=0;e.flashT=0;}cam.x=player.x;cam.y=player.y;';
ok('H01 46 vivos sem dano: render idle byte-idêntico à base (hash)',()=>{const idle=seed=>withSeed(sandbox,seed,()=>{run(H01_PRE);run(H01_SP);sandbox.__ctxLog=[];run('resize();render();');const l=sandbox.__ctxLog;sandbox.__ctxLog=null;return hashLog(l);});const b=beforeWorld();const theirs=withSeed(b.sandbox,155,()=>{b.run(H01_PRE.replace('try{deathVisuals.length=0}catch(e){}',''));b.run(H01_SP);b.sandbox.__ctxLog=[];b.run('resize();render();');const l=b.sandbox.__ctxLog;b.sandbox.__ctxLog=null;return hashLog(l);});assert.strictEqual(idle(155),theirs,'render idle 46 inimigos idêntico ANTES×DEPOIS');});
ok('H02 46 vivos × 300 frames sem dano: estável, sem growth',()=>{fresh();for(let i=0;i<46;i++){const e=enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58);e.aim=0;}for(let f=0;f<300;f++)T.getEnemies().slice().forEach(e=>T.updateEnemy(e,DT));assert.strictEqual(T.getEnemies().length,46);assert.strictEqual(T.getDeathVisuals().length,0);assert.ok(T.getEnemies().every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)));});
ok('H03 46 recebendo hits espaçados: coalesce, sem fila/NaN (sem mortes)',()=>{const p=fresh();const es=[];for(let i=0;i<46;i++)es.push(enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58));for(let f=0;f<300;f++){es.forEach(e=>{if(!e.dead&&e.hp>5)T.damageEnemy(e,1,p.x,p.y,false,false);});es.forEach(e=>{if(!e.dead)T.updateEnemy(e,DT);});}assert.ok(es.every(e=>!e.dead||e.hp>4),'nenhum abate (guarda)');assert.ok(es.every(e=>Object.values(e.visual).filter(v=>typeof v==='number').every(Number.isFinite)));assert.strictEqual(T.getDeathVisuals().length,0);});
ok('H04 46 recebendo dano intenso: bounded, sem NaN',()=>{const p=fresh();const es=[];for(let i=0;i<46;i++)es.push(enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58));for(let f=0;f<120;f++){es.forEach(e=>{if(!e.dead&&e.hp>3)T.damageEnemy(e,2,p.x,p.y,false,false);});es.forEach(e=>{if(!e.dead)T.updateEnemy(e,DT);});}assert.ok(es.every(e=>Object.values(e.visual).filter(v=>typeof v==='number').every(Number.isFinite)));});
ok('H05 25 mortes em sequência: cap respeitado, drena',()=>{const p=fresh();let maxAlive=0;for(let i=0;i<25;i++){const e=enemy('tank',80+(i%10)*58,80+((i/10)|0)*58);T.damageEnemy(e,99999,p.x,p.y,false,false);maxAlive=Math.max(maxAlive,T.getDeathVisuals().length);for(let k=0;k<6;k++)T.deathVisualTick(DT);}assert.ok(maxAlive<=T.DEATH_VISUAL_CAP,'cap durante a sequência');for(let k=0;k<40;k++)T.deathVisualTick(DT);assert.strictEqual(T.getDeathVisuals().length,0,'drenou após o último abate');});
ok('H06 46 mortes quase simultâneas: cap 24, drena em < .5s',()=>{const p=fresh();for(let i=0;i<46;i++){const e=enemy('chaser',80+(i%10)*58,80+((i/10)|0)*58);T.damageEnemy(e,99999,p.x,p.y,false,false);}assert.strictEqual(T.getDeathVisuals().length,24);for(let k=0;k<30;k++)T.deathVisualTick(DT);assert.strictEqual(T.getDeathVisuals().length,0);});
ok('H07 morte em massa de swarm: parts ≤ teto, corpses ≤ cap',()=>{const p=fresh();for(let i=0;i<46;i++){const e=enemy('swarm',80+(i%10)*58,80+((i/10)|0)*58);T.damageEnemy(e,99999,p.x,p.y,false,false);}assert.ok(run('parts.length')<=900,'teto de partículas');assert.strictEqual(T.getDeathVisuals().length,24);for(let k=0;k<20;k++)T.deathVisualTick(DT);assert.strictEqual(T.getDeathVisuals().length,0);});
ok('H08 mistura de famílias morrendo: tudo bounded + args finitos',()=>{const p=fresh();const mix=['tank','bulwark','splitter','phantom','singular','shooter','anomaly','spawner','chaser','swarm','orbiter'];mix.forEach((t,i)=>{const e=enemy(t,100+i*40,200+(i%3)*60);T.damageEnemy(e,99999,p.x,p.y,false,false);});assert.ok(T.getDeathVisuals().length<=11);const l=opsOf(()=>T.drawDeathVisuals());assert.ok(argsFinite(l));for(let k=0;k<30;k++)T.deathVisualTick(DT);assert.strictEqual(T.getDeathVisuals().length,0);});
ok('H09 melee real + mortes: pipeline D intacto (kills acontecem)',()=>{const p=fresh();const wi=T.WEAPONS.findIndex(w=>w.id==='blade');p.owned=[wi];p.wi=wi;p.crit=0;p.fireTimer=0;for(let i=0;i<8;i++){const e=enemy('chaser',p.x+40+i*10,p.y,3);e.hp=Math.min(e.hp,10);e.maxHp=e.hp;}const k0=T.getKills();for(let f=0;f<40;f++){run('player.fireTimer-='+(1/60)+';if(player.fireTimer<=0){fireWeaponFrom(player,WEAPONS[player.wi],\'ally\',1);player.fireTimer=WEAPONS[player.wi].interval;}');T.updateSwings(1/60);T.getEnemies().slice().forEach(e=>T.updateEnemy(e,1/60));}assert.ok(T.getKills()-k0>=1,'melee matou');assert.ok(T.getDeathVisuals().length>=1,'corpse dos abates melee');});
ok('H10 projétil real + morte: pipeline intacto, corpse único',()=>{const p=fresh();p.owned=[RANGED_WI];p.wi=RANGED_WI;p.crit=0;p.fireTimer=0;const e=enemy('swarm',p.x+300,p.y,3);e.aim=0;for(let f=0;f<150;f++){run('player.fireTimer-='+(1/60)+';if(player.fireTimer<=0){fireWeaponFrom(player,WEAPONS[player.wi],\'ally\',1);player.fireTimer=WEAPONS[player.wi].interval;}');T.updateProjectiles(1/60);T.getEnemies().slice().forEach(x=>{if(!x.dead)T.updateEnemy(x,1/60);});if(e.dead)break;}assert.ok(e.dead,'projétil matou');assert.strictEqual(T.getDeathVisuals().length,1,'corpse único');});
ok('H11 render() completo com corpses: sem exceção, args finitos',()=>{const p=fresh();for(let i=0;i<12;i++){const e=enemy(IDS[i%11],100+i*40,200,3);T.damageEnemy(e,99999,p.x,p.y,false,false);}const l=opsOf(()=>run('resize();render();'));assert.ok(argsFinite(l));assert.ok(l.length>0);});
ok('H12 300 frames de combate contínuo: sem crescimento ilimitado',()=>{const p=fresh();const es=[];for(let i=0;i<46;i++)es.push(enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58));let maxC=0,maxP=0;for(let f=0;f<300;f++){es.forEach(e=>{if(!e.dead&&f%3===0)T.damageEnemy(e,4,p.x,p.y,false,false);});es.forEach(e=>{if(!e.dead)T.updateEnemy(e,DT);});T.deathVisualTick(DT);if(es.every(e=>e.dead))es.length=0;maxC=Math.max(maxC,T.getDeathVisuals().length);maxP=Math.max(maxP,run('parts.length'));}assert.ok(maxC<=T.DEATH_VISUAL_CAP,'corpses capped');assert.ok(maxP<=900,'parts capped');});
ok('H13 retorno completo ao estado limpo (FX evaporam no loop real)',()=>{const p=fresh();for(let i=0;i<46;i++){const e=enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58);T.damageEnemy(e,99999,p.x,p.y,false,false);}run('last=performance.now();__t0=performance.now();');let guard=0;while(run('parts.length')>0&&guard<600){run('loop(__t0+=16.667);');guard++;}assert.strictEqual(run('parts.length'),0,'FX do kill evaporou no loop real ('+guard+' frames)');assert.strictEqual(T.getDeathVisuals().length,0,'corpses drenados');T.getEnemies().forEach(e=>assert.ok(!e.dead,'nenhum morto pendente (compactação real)'));T.setEnemies([]);});

/* ============ I · PUREZA, DETERMINISMO, RNG ============ */
ok('I01 drawDeathVisuals sem aleatoriedade (Math.random lança)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const M=sandbox.Math,orig=M.random;M.random=function(){throw new Error('rand no draw');};try{for(let k=0;k<10;k++){T.deathVisualTick(DT);T.drawDeathVisuals();}}finally{M.random=orig;}T.deathVisualClear();});
ok('I02 drawEnemy com hurt (10 tipos sem o jitter legado do anômalo) sem rand novo',()=>{fresh();['chaser','shooter','tank','spawner','swarm','orbiter','bulwark','splitter','phantom','singular'].forEach(id=>{const e=enemy(id,500,400);T.visualNotifyHurt(e,300,400);const M=sandbox.Math,orig=M.random;let err=null;M.random=function(){err=new Error('rand');return 0;};try{T.drawEnemy(e);}catch(ex){err=ex;}finally{M.random=orig;}assert.ok(!err,id+' sem rand em draw com hurt');});});
ok('I03 anomaly: count de rand() igual com/sem hurt (mesmo stream)',()=>{fresh();const e=enemy('anomaly',500,400);const M=sandbox.Math,orig=M.random;let c1=0,c2=0;M.random=function(){c1++;return orig();};T.drawEnemy(e);M.random=function(){c2++;return orig();};T.visualNotifyHurt(e,300,400);T.drawEnemy(e);M.random=orig;assert.strictEqual(c1,c2,'mesma contagem de amostras');});
ok('I04 bloco C: zero relógio de parede/timer/listener/RAF',()=>{const b=DBLOCK();assert.ok(!/Date\.now|performance\.now|setInterval\s*\(|setTimeout\s*\(|addEventListener|requestAnimationFrame/.test(b));});
ok('I05 bloco C: push único em deathVisuals (dentro do cap); sem push em gameplay',()=>{const b=DBLOCK();assert.strictEqual((b.match(/deathVisuals\.push/g)||[]).length,1);assert.ok(!/parts\.push|enemies\.push|projectiles\.push|xporbs\.push|pickups\.push|ftexts\.push/.test(b));});
ok('I06 RNG mecânico: 200 frames de dano → estado+consumo idênticos à base',()=>{const b=beforeWorld();const snap=(sbx,seed)=>withSeed(sbx,seed,()=>{vm.runInContext('startRun();enemies.length=0;projectiles.length=0;player.x=600;player.y=400;player.vx=0;player.vy=0;',sbx);vm.runInContext('var __es=[];for(var i=0;i<6;i++){__es.push(spawnEnemy("chaser",450+i*24,300,3));__es[i].spawnT=0;__es[i].aim=0;}',sbx);let rnd=0;const M=sbx.Math,orig=M.random;M.random=function(){rnd++;sbx.__rnd=rnd;return orig();};for(let f=0;f<200;f++){vm.runInContext('for(var j=0;j<__es.length;j++){var e=__es[j];if(!e.dead)damageEnemy(e,3,586,386,false,false);}',sbx);vm.runInContext('for(var j=0;j<__es.length;j++)if(!__es[j].dead)updateEnemy(__es[j],1/60);',sbx);}M.random=orig;return vm.runInContext('JSON.stringify({st:__es.map(function(e){return [+e.hp.toFixed(6),+e.vx.toFixed(6),+e.vy.toFixed(6),+e.flashT.toFixed(6),e.dead];}),kills:kills,ph:player.hp,coins:player.coins,xb:xporbs.length,ps:parts.length,rnd:__rnd||0})',sbx);});assert.strictEqual(snap(sandbox,4242),snap(b.sandbox,4242),'estado mecânico + consumo de RNG idênticos');});
ok('I07 crit mecânico idêntico à base (kb 70, flash .17)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,777,()=>{vm.runInContext('startRun();enemies.length=0;projectiles.length=0;player.x=600;player.y=400;var e=spawnEnemy("chaser",500,400,3);e.spawnT=0;e.aim=0;damageEnemy(e,5,580,400,true,false);x=[+e.hp.toFixed(6),+e.vx.toFixed(6),+e.vy.toFixed(6),+e.flashT.toFixed(6),e.dead]',sbx);return vm.runInContext('JSON.stringify(x)',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));});
ok('I08 knockback mecânico idêntico à base (kb 40 normal, tank)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,888,()=>{vm.runInContext('startRun();enemies.length=0;player.x=600;player.y=400;var e=spawnEnemy("tank",500,400,3);e.spawnT=0;e.aim=0;e.vx=0;e.vy=0;damageEnemy(e,5,580,400,false,false);x=e.vx.toFixed(6)+","+e.vy.toFixed(6)',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));});
ok('I09 phantom: intangível em ghost (mecânica intacta, igual à base)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,555,()=>{vm.runInContext('startRun();enemies.length=0;var e=spawnEnemy("phantom",500,400,3);e.spawnT=0;e.ghostT=.5;var h0=e.hp;damageEnemy(e,10,580,400,false,false);x=(e.hp===h0)+"|"+(e.visual?e.visual.event:"")',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));assert.strictEqual(r(sandbox),'true|');});
ok('I10 singular: pull mecânico idêntico à base (durante a vida)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,666,()=>{vm.runInContext('startRun();enemies.length=0;player.x=600;player.y=400;player.vx=0;player.vy=0;var e=spawnEnemy("singular",400,400,3);e.spawnT=0;e.aim=0;var __r=[];for(var i=0;i<10;i++){updateEnemy(e,1/60);__r.push(+player.vx.toFixed(5));}x=__r.join(",")',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));assert.notStrictEqual(r(sandbox),'0,0,0,0,0,0,0,0,0,0','pull atua no vivo');});
ok('I11 draw não remove corpse nem muda arrays globais',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,99999,p.x,p.y,false,false);const before=JSON.stringify(T.getDeathVisuals());T.drawDeathVisuals();assert.strictEqual(JSON.stringify(T.getDeathVisuals()),before,'draw é leitura pura');});
ok('I12 scratch global reutilizado (sem alocação por pose)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.visualNotifyHurt(e,p.x-100,p.y);const a=T.visualHurtPose(e),bb=T.visualHurtPose(e);assert.strictEqual(a,bb,'mesmo scratch');});
ok('I13 idle: 46 inimigos × 600 updates sem HURT estado (ataque visual legado ok)',()=>{fresh();for(let i=0;i<46;i++){const e=enemy(IDS[i%11],80+(i%10)*58,80+((i/10)|0)*58);e.aim=0;}for(let f=0;f<600;f++)T.getEnemies().slice().forEach(e=>T.updateEnemy(e,DT));assert.strictEqual(T.getEnemies().filter(e=>e.visual&&e.visual.event==='hurt').length,0,'nenhum HURT criado no idle');assert.strictEqual(T.getDeathVisuals().length,0);});
ok('I14 custo de updateEnemy idle idêntico à base (600 frames, sin count)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,999,()=>{vm.runInContext('startRun();enemies.length=0;var e=spawnEnemy("chaser",500,400,3);e.spawnT=0;e.aim=0;var c=0;var _s=Math.sin;Math.sin=function(){c++;return _s.apply(this,arguments);};for(var i=0;i<600;i++)updateEnemy(e,1/60);Math.sin=_s;x=c',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));});
ok('I15 métricas ON: render com corpses sem erro',()=>{const p=fresh();for(let i=0;i<6;i++){const e=enemy(IDS[i],100+i*40,200,3);T.damageEnemy(e,99999,p.x,p.y,false,false);}run('cfg.metrics=1');const l=opsOf(()=>run('resize();render();'));run('cfg.metrics=0');assert.ok(argsFinite(l));assert.ok(l.length>0);});
ok('I16 métricas OFF: render com corpses sem DOM extra',()=>{const p=fresh();run('cfg.metrics=0');const e=enemy('chaser',600,400);T.damageEnemy(e,99999,500,400,false,false);const l=opsOf(()=>run('resize();render();'));assert.ok(l.length>0);});

/* ============ J · COMPARAÇÃO MECÂNICA COMPLETA ============ */
ok('J01 EDEFS cobre 11 tipos com stats válidos',()=>{const a=Object.entries(T.EDEFS);assert.strictEqual(a.length,11);a.forEach(([k,v])=>{assert.ok(v.hp>0&&v.spd>0&&v.r>0&&v.dmg>0&&v.xp>0&&v.color&&Array.isArray(v.tags),'EDEFS.'+k);});});
ok('J02 WEAPONS idêntico à base (dano/cadência/efeitos)',()=>{const b=beforeWorld();T.WEAPONS.forEach((w,i)=>{assert.strictEqual(JSON.stringify(w),JSON.stringify(b.T.WEAPONS[i]),'WEAPONS['+i+'] '+w.id);});});
ok('J03 MINIBOSS idêntico à base',()=>assert.strictEqual(JSON.stringify(T.MINIBOSS),JSON.stringify(beforeWorld().T.MINIBOSS)));
ok('J04 waveCompBase idêntico em 20 ondas',()=>{const b=beforeWorld();for(let w=1;w<=20;w++)assert.strictEqual(JSON.stringify(T.waveComp(w)),JSON.stringify(b.T.waveComp(w)),'onda '+w);});
ok('J05 spawnBoss: objeto idêntico à base (semente igual p/ o sorteio de mode)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,31337,()=>{vm.runInContext('startRun();enemies.length=0;spawnBoss();x=JSON.stringify({hp:boss.hp,maxHp:boss.maxHp,dmg:boss.dmg,spd:boss.spd,r:boss.r,xp:boss.xp,mode:boss.mode,beamN:boss.beamN,shockT:boss.shockT,gravT:boss.gravT,dashCd:boss.dashCd,intro:boss.intro})',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));});
ok('J06 dano/cadência das 27 armas idênticos',()=>{const b=beforeWorld();T.WEAPONS.forEach((w,i)=>{assert.strictEqual(w.dmg,b.T.WEAPONS[i].dmg,w.id);assert.strictEqual(w.interval,b.T.WEAPONS[i].interval,w.id);});});
ok('J07 splitter mecânica idêntica à base (filhos: count/pos/stats, semente)',()=>{const b=beforeWorld();const r=sbx=>withSeed(sbx,99,()=>{vm.runInContext('startRun();enemies.length=0;projectiles.length=0;player.x=600;player.y=400;var e=spawnEnemy("splitter",500,400,3);e.spawnT=0;e.aim=0;damageEnemy(e,99999,580,400,false,false);var ks=enemies.filter(function(q){return q.isShard;});x=ks.length+"|"+ks.map(function(q){return [+q.x.toFixed(3),+q.y.toFixed(3),+q.r.toFixed(4),+q.hp.toFixed(4),+q.spd.toFixed(4),q.xp];}).join("~")',sbx);return vm.runInContext('x',sbx);});assert.strictEqual(r(sandbox),r(b.sandbox));});
ok('J08 status damage pipeline intacto (DoT aplica + hurt)',()=>{const p=fresh();const e=enemy('chaser',p.x+100,p.y);T.damageEnemy(e,3,p.x,p.y,false,true);assert.ok(e.hp<e.maxHp);assert.strictEqual(e.visual.event,'hurt');});
ok('J09 projétil mecânico intacto (acerta uma vez e aplica dano)',()=>{const p=fresh();const e=enemy('chaser',p.x+300,p.y);const hp0=e.hp;run('projectiles.length=0;projectiles.push({x:player.x+20,y:player.y,vx:500,vy:0,r:5,dmg:7,life:5,type:WEAPONS['+RANGED_WI+'].id,team:"ally",color:"#fff",aoe:0,pierce:0,crit:false,hits:null,owner:player,def:WEAPONS['+RANGED_WI+'],dist:0,maxDist:900,srcC:"player"})');for(let f=0;f<150&&e.hp>=hp0;f++)T.updateProjectiles(DT);assert.ok(e.hp<hp0,'projétil acertou');assert.ok(!e.dead||e.hp<=0,'dano < hp mantém vivo ou mata');});
ok('J10 melee mecânico intacto (arco atinge no raio real)',()=>{const p=fresh();const wi=T.WEAPONS.findIndex(w=>w.id==='blade');p.owned=[wi];p.wi=wi;p.crit=0;const e=enemy('chaser',p.x+50,p.y);const hp0=e.hp;run('fireMelee(player,WEAPONS['+wi+'],\'ally\',1)');assert.ok(e.hp<hp0,'melee acertou no arco real');});
ok('J11 reward pipeline intacto: coins+xp por kill',()=>{const p=fresh();const e=enemy('shooter',p.x+100,p.y);run('curAttacker=player;pickups.length=0');const c0=p.coins+run('pickups.filter(k=>k.type==="coin").reduce((a,k)=>a+k.v,0)');T.damageEnemy(e,99999,p.x,p.y,false,false);run('curAttacker=null');const c1=p.coins+run('pickups.filter(k=>k.type==="coin").reduce((a,k)=>a+k.v,0)');assert.ok(c1>c0,'créditos do drop aplicados');assert.strictEqual(run('xporbs.reduce((a,o)=>a+o.v,0)'),e.xp,'xp');});
ok('J12 killEnemy preserva corpse/recompensa e isola kill-proc temporal',()=>{const mine=SRC.match(/function killEnemy\(e,damageSource\)\{[\s\S]*?\n\}/);assert.ok(mine);assert.ok(mine[0].includes('deathVisualPush(e)'));assert.ok(mine[0].includes("itemEmit('onKill'"));assert.ok(mine[0].includes('!isTemporalDamageSource(damageSource)'));});
ok('J13 damageEnemy re-baselineado: source temporal explícito e pipeline normal preservado',()=>{const mine=SRC.match(/function damageEnemy\(e,d,srcx,srcy,crit,isDot,damageSource\)\{[\s\S]*?\n\}/);assert.ok(mine);assert.strictEqual(crypto.createHash('sha256').update(mine[0]).digest('hex'),'7e08463b4dbf4d11613cb12f1fd64c0342b8faaa3344c394e2eb2f2089686c43');assert.ok(mine[0].includes("e.elite==='shield'"));assert.ok(mine[0].includes("itemEmit('onHit'"));});
ok('J14 updateEnemy preserva estrutura mecânica',()=>{const h=src=>crypto.createHash('sha256').update(src.match(/function updateEnemy\(e,dt\)\{[\s\S]*?\n\}/)[0]).digest('hex');assert.strictEqual(h(SRC),'dabbbf648ddb4b427a4570ddde4944dd530c9fb2531791a0ca28c6ff76b475ec');});

/* ============ K · ROBUSTEZ FINAL ============ */
ok('K01 corpse com type inválido: draw no-op seguro',()=>{T.deathVisualClear();T.setDeathVisuals([{x:500,y:400,r:10,type:'__x__',color:'#fff',aim:0,dir:0,t:.01,dur:.2,seed:.5}]);const l=opsOf(()=>T.drawDeathVisuals());T.deathVisualClear();assert.strictEqual(nOp(l,'beginPath'),0);assert.ok(argsFinite(l));});
ok('K02 seed/dur/aim/dir/t NaN injetados: draw finito',()=>{T.deathVisualClear();T.setDeathVisuals([{x:500,y:400,r:10,type:'chaser',color:'#fff',aim:NaN,dir:NaN,t:NaN,dur:NaN,seed:NaN}]);const l=opsOf(()=>T.drawDeathVisuals());T.deathVisualClear();assert.ok(argsFinite(l),'NaN não propaga para o canvas');});
ok('K03 5000 mortes sequenciais: bounded',()=>{const p=fresh();for(let i=0;i<5000;i++){const e=enemy('swarm',500,400,3);T.damageEnemy(e,99999,p.x,p.y,false,false);if(i%5===0)T.deathVisualTick(DT);}assert.ok(T.getDeathVisuals().length<=T.DEATH_VISUAL_CAP);T.deathVisualClear();});
ok('K04 drawDeathVisuals não consome RNG em stress',()=>{const p=fresh();for(let i=0;i<20;i++){const e=enemy(IDS[i%11],100+i*30,200,3);T.damageEnemy(e,99999,p.x,p.y,false,false);}const M=sandbox.Math,orig=M.random;let c=0;M.random=function(){c++;return orig();};for(let k=0;k<30;k++){T.deathVisualTick(DT);T.drawDeathVisuals();}M.random=orig;assert.strictEqual(c,0,'zero rand em 30 frames de corpse');T.deathVisualClear();});

console.log('\nResultado: '+passed+' passaram · '+failed+' falharam');
if(failed)process.exit(1);
